### ISSUE TITLE
No code documentation

### ISSUE THREAD

**Issue by rakshazi** [PHPixie/Console#1]
Hello!
Please, add docblocks documentation with description, params and return values to the code and type of params in methods.

Best regards, Nikita.

**Comment by dracony** [comment]
I will =)

But the general usage docs you can already see on the website

**Comment by rakshazi** [comment]
Thank you!

I know about docs on site, but I prefer docs in code :)

**Comment by dracony** [comment]
Sure, I'll work on those =)
