### ISSUE TITLE
Call to undefined method Project\App\Console\Migrate::usage()

### ISSUE THREAD

**Issue by rakshazi** [PHPixie/Console#2]
Hello!

When you try to call console command without required arguements, you see this error message: `[ERROR]: Missing argument: action` and `Error Object` exception throws with message `Call to undefined method Project\App\Console\[YourCommand]::usage()`

Steps to reproduce:
1. Create any console command class
2. Add required argument (`action` in my case)
3. Call command via `./console app:<yourcommand>` without required argument

Expected behaviour:
When you missed required argument, only error message `[ERROR]: Missing argument: <argument>` must be shown (whithout printing `Error Object` exception)

**Comment by dracony** [comment]
Ah, I see. I'll fix that! Thanks!
